name: Label AI Assistance

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  label-ai-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Add a single ai-assisted label based on selected level
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || "";
            const number = pr.number;

            // Match checkboxes like [x], [X], [ x ], [ X ] etc. case- and space-insensitive
            const checked = (label) => {
              const pattern = new RegExp(`- \\[\\s*[xX]\\s*\\] \\*\\*${label}\\*\\*`);
              return pattern.test(body);
            };

            const hasLight = checked("Light");
            const hasMedium = checked("Medium");
            const hasHeavy = checked("Heavy");

            let labelToAdd = null;

            if (hasHeavy) {
              labelToAdd = "ai-assisted/heavy";
            } else if (hasMedium) {
              labelToAdd = "ai-assisted/medium";
            } else if (hasLight) {
              labelToAdd = "ai-assisted/light";
            }

            if (labelToAdd) {
              const existingLabels = pr.labels.map(label => label.name);
              if (!existingLabels.includes(labelToAdd)) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: number,
                  labels: [labelToAdd]
                });
              }
            }

